---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: create-topic
spec:
  selector:
    matchLabels:
      app: create-topic
  template:
    metadata:
      name: create-topic
      labels:
        app: create-topic
    spec:
      containers:
      - name: create-topic
        image: ches/kafka
        command: ["kafka-topics.sh"]
        args: ["--create --topic test1 --replication-factor 3 --partitions 2 --zookeeper zoo1:2181"]
      restartPolicy: Never