---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: create-topic
spec:
  selector:
    matchLabels:
      app: create-topic
  template:
    metadata:
      name: create-topic
      labels:
        app: create-topic
    spec:
      containers:
      - name: create-topic
        image: ches/kafka
        command: ["kafka-topics.sh"]
        args: ["--create --topic my-topic --replication-factor 1 --partitions 1 --zookeeper $(KAFKA_SERVICE_PORT_2181_TCP_ADDR):2181"]
      restartPolicy: Never